modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Wulian233/ChatAnimation/issues"
license = "MIT"

[[mods]]
modId = "chatanimation"
version = "${version}"
displayName = "Chat Animation"
displayURL = "https://github.com/Wulian233/ChatAnimation"
authors = "Wulian233"
description = '''
Makes chat messages appear with a smooth animation.
'''
#logoFile = "icon.png"

[[mixins]]
config = "chatanimation.mixins.json"

[[mixins]]
config = "chatanimation.neoforge.mixins.json"

[[dependencies.chatanimation]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatanimation]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
